/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trustframework.data;

import java.util.Date;
import trustframework.graph.TFGraph;

/**
 *
 * @author guilherme
 */
public interface DataExtractor {
    
    /**
     * Retrieve project data for the given repostiory (owner/name) sice a given date
     * @param owner repository owner
     * @param name repository name
     * @param since date that limits data retrieval 
     * @return project data
     */
    public Object getProjectData(String owner, String name, Date since);
    
    /**
     * Generate a relations graph from project data. A relations graph, is a graph where vertex represent users involved in project. The edges in this graph are labeled with
     * a pull request id. If there is an edge between two users, it means that they appear in a pull request.
     * @param projectData project data
     * @param graph instance of graph
     * @return the relations graph
     */
    public TFGraph generateRelationsGraph(Object projectData, TFGraph graph);
    
    /**
     * Update the graph generated by {@link #generateRelationsGraph(java.lang.Object, trustframework.graph.TFGraph) } removing old edges and adding new if necessary.
     * @param relations old relations graph.
     * @param projectData project data.
     * @param limit limit date. Edges before this date will be excluded.
     */
    public void updateRelationsGraph(TFGraph relations, Object projectData, Date limit);
}
